Remove @jit annotation for NormalizeShells
For two reasons:
1. There is a comment above it that tells us to keep it off.
2. The program crashes somewhere in it due to an index out of range error in its current state:

Traceback (most recent call last):
  File "/software/presto/e/rovanion/software/3DFSC/3.1-foss-2021a-CUDA-11.3.1/bin/run3DFSC", line 8, in <module>
    sys.exit(main())
  File "/software/presto/e/rovanion/software/3DFSC/3.1-foss-2021a-CUDA-11.3.1/lib/python3.9/site-packages/ThreeDFSC/T\
hreeDFSC_Start.py", line 200, in main
    execute(options, parser)
  File "/software/presto/e/rovanion/software/3DFSC/3.1-foss-2021a-CUDA-11.3.1/lib/python3.9/site-packages/ThreeDFSC/T\
hreeDFSC_Start.py", line 124, in execute
    tdfsc_2017.main(halfmap1,halfmap2,options.ThreeDFSC,options.apix,options.dthetaInDegrees,gpu=options.gpu)
  File "/software/presto/e/rovanion/software/3DFSC/3.1-foss-2021a-CUDA-11.3.1/lib/python3.9/site-packages/ThreeDFSC/p\
rograms/ThreeDFSC_ReleaseAug2017.py", line 1124, in main
    NormalizeShells(nx,ny,nz,kXofR,kYofR,kZofR,inc,retofROutR, retofROutI, n1ofROut,n2ofROut, NumAtEachR, RMax);
IndexError: index 8 is out of bounds for axis 0 with size 8